### ISSUE TITLE
Go 1.21 Support

### ISSUE THREAD

**Issue by dstrelau** [pyroscope-io/godeltaprof#4]
Hello! I just tried to build our project using this with Go 1.21 and it looks like there might be some updates needed:

```
# github.com/pyroscope-io/godeltaprof/internal/pprof
../../../../pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.1/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../../../../pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.1/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
```

I don't have any idea what any of this means, but happy to provide more info or help where I can. Thank you!

**Comment by korniltsev** [comment]
Fixed in https://github.com/grafana/godeltaprof/pull/5
