### ISSUE TITLE
runtime_expandFinalInlineFrame

### ISSUE THREAD

**Issue by chensanle** [pyroscope-io/godeltaprof#7]
../../vendor/github.com/pyroscope-io/godeltaprof/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../../vendor/github.com/pyroscope-io/godeltaprof/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame

go 1.21.0

**Comment by korniltsev** [comment]
https://github.com/grafana/godeltaprof/commit/0ae33824c1b70ea9dbc188bee460f46880827ad7
Was fixed in latest release
